### PR TITLE
[PKG-4789] Initial build 0.1.800

### PR DESCRIPTION
**Pull request by ViridianMelody**
autoviml 0.1.800 :snowflake:

**Destination channel:** Snowflake

### Links

- [PKG-4789]
- [Upstream repository](https://github.com/AutoViML/Auto_ViML)
- Relevant dependency PRs:
  - https://github.com/AnacondaRecipes/emoji-feedstock/pull/2
  - https://github.com/AnacondaRecipes/imbalanced-ensemble-feedstock/pull/1

### Explanation of changes:

- Patched 2 broken imports in upstream:
  - `imbalanced_ensemble` -> `imbens`
  - `scipy.interp` -> `numpy.interp`
    - `scipy.interp` has been deprecated in favor of `numpy.interp`, and removed since `scipy 1.12`.
  - Submitted a PR to upstream with the same fix.
- No upstream tests available.

[PKG-4789]: https://anaconda.atlassian.net/browse/PKG-4789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by lorepirri — COMMENTED** [review]
Nice work with the patches and the undeclared dep (`networkx`),

You could add a smoke test as in https://github.com/AutoViML/Auto_ViML/blob/master/README.md#usage

Setting `test=""` and considering:

> Boosting_Flag: It is recommended that you first set Boosting_Flag=None to get a Linear model. Once you understand that, then you can try to set Boosting_Flag=False to get a Random Forest model. Finally, try Boosting_Flag=True to get an XGBoost model. 

We could set `Boosting_Flag` in order:

1. `Boosting_Flag=None`
2 `Boosting_Flag=False`.
3. `Boosting_Flag=True`

I have no idea if it will work out of the box. If not, let's skip this.

We changed the upper bound of `xgboost` and are not testing it.

**Comment by ViridianMelody** [comment]
@lorepirri It would seem that the upstream `xgboost` pinning is necessary. Running the code in the example notebook fails for `xgboost >=1.7,<2.0`, but works fine with the upstream pinnings. We can either proceed with the rebuild for `xgboost` or deliver only Python 3.9 and 3.10 versions.

**Comment by lorepirri** [comment]
in `1.7.0` they changed things, we need the `1.5.1` rebuild in 
https://github.com/AnacondaRecipes/xgboost-feedstock/pull/15

**Pull request merged**
