### PR TITLE
[PKG-5467] Rebuild 0.1.800

### PR DESCRIPTION
**Pull request by ViridianMelody**
autoviml 0.1.800 :snowflake:

**Destination channel:** Snowflake

### Links

- [PKG-5467] 
- [Upstream repository](https://github.com/AutoViML/Auto_ViML/)

### Explanation of changes:

- Pinning an exact build for `imbalanced-ensemble` to prevent broken older build from pulling in.

[PKG-5467]: https://anaconda.atlassian.net/browse/PKG-5467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by danpetry — COMMENTED** [review]
- are you going to do a further build with `imbalanced-ensemble >=0.2.2`?
- do you know why imbalanced-ensemble 0.2.2 wasn't being pulled into scikit-learn? excluding the build you don't want doesn't mean the new version will be pulled in, you might just get a solver error, right?
- has the new imbalanced-ensemble been tested successfully with scikit-learn, i.e. has the whole solution been validated?

**Comment by ViridianMelody** [comment]
> * are you going to do a further build with `imbalanced-ensemble >=0.2.2`?
> * do you know why imbalanced-ensemble 0.2.2 wasn't being pulled into scikit-learn? excluding the build you don't want doesn't mean the new version will be pulled in, you might just get a solver error, right?

`imbalanced-ensemble 0.2.2` wasn't being pulled in because it requires `pandas >=2.1.1`, while `autoviml` requires `pandas<2.0`, so they're fundamentally incompatible.

> * has the new imbalanced-ensemble been tested successfully with scikit-learn, i.e. has the whole solution been validated?

Yes, it passed the same tests as the original build in the PR linked below. Notably, the tests for `autoviml` also fail if I remove the build restriction on a local build.
https://github.com/AnacondaRecipes/imbalanced-ensemble-feedstock/pull/3

**Comment by danpetry** [comment]
> the tests for autoviml also fail if I remove the build restriction on a local build

with a local build from the main branch of autoviml I get the right versions of imbalanced-ensemble (0.2.1 b1) and scikit-learn (1.4.2) pulled in, and tests pass. I guess the higher build number of imb-ens and the lower version of sk-learn is chosen for some reason? I guess this PR eliminates the bad combination, which would also be a valid solve?

**Review by danpetry — APPROVED** [review]

**Review by lorepirri — APPROVED** [review]
LGTM, it sources the correct version, thank you!

```
imbalanced-ensemble:       0.2.1-py311hd43f75c_1 
```

**Pull request merged**
